<?php
/**
*	Global vars Page
*	
*	Serial:		120429
*	by:			M.Karminski
*
*/

//------  -[ Global Page SWITCH Vars ]-  ------
//All these vars are used in switch page and array.
$SEMESTER_PAGE_SWITCH 				= 1;
$COURSE_TYPE_PAGE_SWITCH			= 2;
$COURSE_PAGE_SWITCH 				= 3;
$CLASS_PAGE_SWITCH					= 4;
$COURSE_PERIOD_PAGE_SWITCH			= 5;
$WEEKS_SCHEDULE_PAGE_SWITCH 		= 6;
$TOTAL_SCHEDULE_PAGE_SWITCH			= 7;
$CLASSROOM_PAGE_SWITCH				= 8;
$TEACHER_PAGE_SWITCH				= 9;
$CLASSROOM_SCHEDULE_PAGE_SWITCH		= 10;

$STUDENTS_SCHEDULE_PAGE_SWITCH		= 12;

$COURSE_IMPORT_PAGE_SWITCH			= 13;
$CLASS_IMPORT_PAGE_SWITCH			= 14;
$SETTINGS_PAGE_SWITCH				= 15;

//TODO:Replace all "THIS" method.[IMPORTANT]
//TODO:Chage the include files place.
//TODO:Add Table delete method.[IMPORTANT]
//TODO:COURSE_TYPE->COURSE_MODE, COURSE_STYLE->COURSE_TYPE.[IMPORTANT]

//------  -[ Config of editable file locate ]-  ------
$EDITABLE_GRID_UPDATE_PAGE_NAME = 'functions/editable_grid_update.php';
$EDITABLE_GRID_LOADDATA_PAGE_NAME = 'functions/editable_grid_loaddata.php';

//------  -[ Course Day of a Week ]-  ------
//Course day of a week.
$COURSE_DAY_OF_A_WEEK = 5;

//------  -[ Course in a Day ]-  ------
//How much course in a day.
$COURSE_IN_A_DAY = 4;

//------  -[ One Course Period ]-  ------
//One course equal two course period
$ONE_COURSE_PERIOD = 2;

//-----  -[ Semester Week Number ]-  ------
//How much week in a semester
$SEMESTER_WEEK_NUMBER = 20;

//------  -[ Max Take Course a Week ]-  ------
//The max value of take course in a week 
$MAX_TAKE_COURSE_A_WEEK = $COURSE_DAY_OF_A_WEEK * $COURSE_IN_A_DAY * $ONE_COURSE_PERIOD;

//------ -[ Global Page Informatin Vars ]-  ------
//
//[ WARING:All VALUES ARE USED IN GLOBAL, CHANGE IT CAREFULLY ]
//
//$PAGE_INFO_ARRAY			For global page infromations
//$TABLE_KEY_NAMES_ARRAY 	For database table key names and vars key names
//$TABLE_KEY_TYPES_ARRAY 	For database table key types, was only used in table creating 

$PAGE_INFO_ARRAY[0]['PAGE_NAME'] 					= "index";				
$PAGE_INFO_ARRAY[0]['PAGE_NAME_IN_CHINESE'] 		= "首页";		
$PAGE_INFO_ARRAY[0]['FILE_NAME']					= "index.php";

$PAGE_INFO_ARRAY[1]['PAGE_NAME']			 		= "Semester Manage";
$PAGE_INFO_ARRAY[1]['PAGE_NAME_IN_CHINESE'] 		= "学期管理";
$PAGE_INFO_ARRAY[1]['FILE_NAME'] 					= "semester_manage.php";
$PAGE_INFO_ARRAY[1]['TABLE_NAME'] 					= "SEMESTER";
$TABLE_KEY_NAMES_ARRAY[1]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[1]['SEMESTER'] 				= "SEMESTER";
$TABLE_KEY_NAMES_ARRAY[1]['PART'] 					= "PART";
$TABLE_KEY_NAMES_ARRAY[1]['START_YEAR'] 			= "START_YEAR";
$TABLE_KEY_NAMES_ARRAY[1]['START_MONTH'] 			= "START_MONTH";
$TABLE_KEY_NAMES_ARRAY[1]['START_DAY'] 				= "START_DAY";
$TABLE_KEY_NAMES_ARRAY[1]['WEEK_COUNT'] 			= "WEEK_COUNT";
$TABLE_KEY_TYPES_ARRAY[1]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[1]['SEMESTER'] 				= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[1]['PART'] 					= "int";
$TABLE_KEY_TYPES_ARRAY[1]['START_YEAR'] 			= "int";
$TABLE_KEY_TYPES_ARRAY[1]['START_MONTH'] 			= "int";
$TABLE_KEY_TYPES_ARRAY[1]['START_DAY'] 				= "int";
$TABLE_KEY_TYPES_ARRAY[1]['WEEK_COUNT'] 			= "int";

$PAGE_INFO_ARRAY[2]['PAGE_NAME'] 					= "Course Type Manage";
$PAGE_INFO_ARRAY[2]['PAGE_NAME_IN_CHINESE'] 		= "模块管理";
$PAGE_INFO_ARRAY[2]['FILE_NAME']					= "course_type_manage.php";
$PAGE_INFO_ARRAY[2]['TABLE_NAME']					= "COURSE_TYPE";
$TABLE_KEY_NAMES_ARRAY[2]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[2]['COURSE_TYPE']			= "COURSE_TYPE";
$TABLE_KEY_NAMES_ARRAY[2]['COURSE_TOTAL_PERIOD']	= "COURSE_TOTAL_PERIOD";
$TABLE_KEY_TYPES_ARRAY[2]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[2]['COURSE_TYPE']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[2]['COURSE_TOTAL_PERIOD']	= "int";

$PAGE_INFO_ARRAY[3]['PAGE_NAME'] 					= "Course Manage";
$PAGE_INFO_ARRAY[3]['PAGE_NAME_IN_CHINESE'] 		= "课程管理";
$PAGE_INFO_ARRAY[3]['FILE_NAME']					= "course_manage.php";
$PAGE_INFO_ARRAY[3]['TABLE_NAME']					= "COURSE";
$TABLE_KEY_NAMES_ARRAY[3]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[3]['COURSE_NAME']			= "COURSE_NAME";
$TABLE_KEY_NAMES_ARRAY[3]['COURSE_KEY_NAME']		= "COURSE_KEY_NAME";
$TABLE_KEY_NAMES_ARRAY[3]['COURSE_CAPABILITY']  	= "COURSE_CAPABILITY";
$TABLE_KEY_NAMES_ARRAY[3]['COURSE_STYLE']			= "COURSE_STYLE";
$TABLE_KEY_TYPES_ARRAY[3]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[3]['COURSE_NAME']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[3]['COURSE_KEY_NAME']		= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[3]['COURSE_CAPABILITY']		= "int";
$TABLE_KEY_TYPES_ARRAY[3]['COURSE_STYLE']			= "varchar(15)";

$PAGE_INFO_ARRAY[4]['PAGE_NAME'] 					= "Class Manage";
$PAGE_INFO_ARRAY[4]['PAGE_NAME_IN_CHINESE'] 		= "班级管理";
$PAGE_INFO_ARRAY[4]['FILE_NAME']					= "class_manage.php";
$PAGE_INFO_ARRAY[4]['TABLE_NAME']					= "CLASS";
$TABLE_KEY_NAMES_ARRAY[4]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[4]['CLASS_TYPE']				= "CLASS_TYPE";
$TABLE_KEY_NAMES_ARRAY[4]['CLASS_NAME']				= "CLASS_NAME";
$TABLE_KEY_NAMES_ARRAY[4]['CLASS_CAPABILITY']		= "CLASS_CAPABILITY";
//$TABLE_KEY_NAMES_ARRAY[4]['WEEK']					= "WEEK_";
//...
$TABLE_KEY_TYPES_ARRAY[4]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[4]['CLASS_TYPE']				= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[4]['CLASS_NAME']				= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[4]['CLASS_CAPABILITY']		= "int";
//$TABLE_KEY_TYPES_ARRAY[4]['WEEK']					= "varchar(15)";	//The type "varchar(15)" is requird
//...

$PAGE_INFO_ARRAY[5]['PAGE_NAME'] 					= "Course Period Manage";
$PAGE_INFO_ARRAY[5]['PAGE_NAME_IN_CHINESE'] 		= "学时管理";
$PAGE_INFO_ARRAY[5]['FILE_NAME']					= "course_period_manage.php";
$GRID_KEY_NAMES_ARRAY[5]['id']						= "id";
$GRID_KEY_NAMES_ARRAY[5]['COURSE_NAME']				= "课程名称";
$GRID_KEY_NAMES_ARRAY[5]['COURSE_CAPABILITY']		= "课程班级容量";
$GRID_KEY_NAMES_ARRAY[5]['COURSE_STYLE']			= "课程代码";
$GRID_KEY_NAMES_ARRAY[5]['A']						= "A学时";
$GRID_KEY_NAMES_ARRAY[5]['B']						= "B学时";
$GRID_KEY_NAMES_ARRAY[5]['C1']						= "C1学时";
$GRID_KEY_NAMES_ARRAY[5]['C2']						= "C2学时";
$GRID_KEY_NAMES_ARRAY[5]['C3']						= "C3学时";
$GRID_KEY_NAMES_ARRAY[5]['D1']						= "D1学时";
$GRID_KEY_NAMES_ARRAY[5]['D2']						= "D2学时";
$GRID_KEY_NAMES_ARRAY[5]['D3']						= "D3学时";

$PAGE_INFO_ARRAY[6]['PAGE_NAME'] 					= "Weeks Schedule Manage";
$PAGE_INFO_ARRAY[6]['PAGE_NAME_IN_CHINESE'] 		= "周课表管理";
$PAGE_INFO_ARRAY[6]['FILE_NAME']					= "weeks_schedule_manage.php";
$GRID_KEY_NAMES_ARRAY[6]['id']						= "id";
$GRID_KEY_NAMES_ARRAY[6]['CLASS_TYPE']				= "班级类型";
$GRID_KEY_NAMES_ARRAY[6]['CLASS_NAME']				= "班级名称";
$GRID_KEY_NAMES_ARRAY[6]['CLASS_CAPABILITY']		= "班级容量";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_0']					= "学期第1周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_1']					= "学期第2周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_2']					= "学期第3周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_3']					= "学期第4周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_4']					= "学期第5周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_5']					= "学期第6周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_6']					= "学期第7周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_7']					= "学期第8周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_8']					= "学期第9周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_9']					= "学期第10周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_10']					= "学期第11周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_11']					= "学期第12周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_12']					= "学期第13周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_13']					= "学期第14周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_14']					= "学期第15周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_15']					= "学期第16周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_16']					= "学期第17周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_17']					= "学期第18周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_18']					= "学期第19周";
$GRID_KEY_NAMES_ARRAY[6]['WEEK_19']					= "学期第20周";

$PAGE_INFO_ARRAY[7]['PAGE_NAME'] 					= "Total Schedule Manage";
$PAGE_INFO_ARRAY[7]['PAGE_NAME_IN_CHINESE'] 		= "总课表管理";
$PAGE_INFO_ARRAY[7]['FILE_NAME']					= "total_schedule_manage.php";
$PAGE_INFO_ARRAY[7]['TABLE_NAME']					= "TOTAL_SCHEDULE";
$TABLE_KEY_NAMES_ARRAY[7]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[7]['SEMESTER_WEEK']			= "SEMESTER_WEEK";
$TABLE_KEY_NAMES_ARRAY[7]['WEEK']					= "WEEK";
//$TABLE_KEY_NAMES_ARRAY[7]['COURSE_0_0']			= "COURSE_0_0";
//...
$TABLE_KEY_TYPES_ARRAY[7]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[7]['SEMESTER_WEEK']			= "int";
$TABLE_KEY_TYPES_ARRAY[7]['WEEK']					= "int";
//$TABLE_KEY_TYPES_ARRAY[7]['COURSE_0_0']			= "varchar(15)";
//...
$GRID_KEY_NAMES_ARRAY[7]['id']						= "ID";
$GRID_KEY_NAMES_ARRAY[7]['SEMESTER_WEEK']			= "学期周";
$GRID_KEY_NAMES_ARRAY[7]['WEEK']					= "星期";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_0_0']				= "课程0第12节";				
$GRID_KEY_NAMES_ARRAY[7]['COURSE_0_1']				= "课程0第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_0_2']				= "课程0第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_0_3']				= "课程0第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_1_0']				= "课程1第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_1_1']				= "课程1第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_1_2']				= "课程1第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_1_3']				= "课程1第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_2_0']				= "课程2第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_2_1']				= "课程2第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_2_2']				= "课程2第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_2_3']				= "课程2第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_3_0']				= "课程3第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_3_1']				= "课程3第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_3_2']				= "课程3第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_3_3']				= "课程3第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_4_0']				= "课程4第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_4_1']				= "课程4第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_4_2']				= "课程4第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_4_3']				= "课程4第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_5_0']				= "课程5第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_5_1']				= "课程5第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_5_2']				= "课程5第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_5_3']				= "课程5第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_6_0']				= "课程6第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_6_1']				= "课程6第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_6_2']				= "课程6第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_6_3']				= "课程6第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_7_0']				= "课程7第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_7_1']				= "课程7第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_7_2']				= "课程7第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_7_3']				= "课程7第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_8_0']				= "课程8第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_8_1']				= "课程8第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_8_2']				= "课程8第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_8_3']				= "课程8第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_9_0']				= "课程9第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_9_1']				= "课程9第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_9_2']				= "课程9第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_9_3']				= "课程9第78节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_10_0']				= "课程10第12节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_10_1']				= "课程10第34节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_10_2']				= "课程10第56节";
$GRID_KEY_NAMES_ARRAY[7]['COURSE_10_3']				= "课程10第78节";

$PAGE_INFO_ARRAY[8]['PAGE_NAME'] 					= "Classroom Manage";
$PAGE_INFO_ARRAY[8]['PAGE_NAME_IN_CHINESE'] 		= "教室管理";
$PAGE_INFO_ARRAY[8]['FILE_NAME']					= "classroom_manage.php";
$PAGE_INFO_ARRAY[8]['TABLE_NAME']					= "CLASSROOM";
$TABLE_KEY_NAMES_ARRAY[8]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[8]['CLASSROOM_NAME']			= "CLASSROOM_NAME";
$TABLE_KEY_NAMES_ARRAY[8]['CLASSROOM_TYPE']			= "CLASSROOM_TYPE";
$TABLE_KEY_NAMES_ARRAY[8]['CLASSROOM_CAPABILITY']	= "CLASSROOM_CAPABILITY";
$TABLE_KEY_TYPES_ARRAY[8]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[8]['CLASSROOM_NAME']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[8]['CLASSROOM_TYPE']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[8]['CLASSROOM_CAPABILITY']	= "varchar(15)";

$PAGE_INFO_ARRAY[9]['PAGE_NAME'] 					= "Teachers Manage";
$PAGE_INFO_ARRAY[9]['PAGE_NAME_IN_CHINESE'] 		= "教师管理";
$PAGE_INFO_ARRAY[9]['FILE_NAME']					= "teachers_manage.php";
$PAGE_INFO_ARRAY[9]['TABLE_NAME']					= "TEACHER";
$TABLE_KEY_NAMES_ARRAY[9]['id']						= "id";
$TABLE_KEY_NAMES_ARRAY[9]['TEACHER_NAME']			= "TEACHER_NAME";
$TABLE_KEY_NAMES_ARRAY[9]['TEACHER_TYPE_INTRO']		= "TEACHER_TYPE_INTRO";
$TABLE_KEY_NAMES_ARRAY[9]['TEACHER_TYPE_DESIGN']	= "TEACHER_TYPE_DESIGN";
$TABLE_KEY_NAMES_ARRAY[9]['TEACHER_TYPE_EXAM']		= "TEACHER_TYPE_EXAM";
$TABLE_KEY_NAMES_ARRAY[9]['TEACHER_TYPE_TRAIN']		= "TEACHER_TYPE_TRAIN";
$TABLE_KEY_NAMES_ARRAY[9]['TEACH_FREQUENCY_INTRO']	= "TEACH_FREQUENCY_INTRO";
$TABLE_KEY_NAMES_ARRAY[9]['TEACH_FREQUENCY_DESIGN']	= "TEACH_FREQUENCY_DESIGN";
$TABLE_KEY_NAMES_ARRAY[9]['TEACH_FREQUENCY_EXAM']	= "TEACH_FREQUENCY_EXAM";
$TABLE_KEY_NAMES_ARRAY[9]['TEACH_FREQUENCY_TRAIN']	= "TEACH_FREQUENCY_TRAIN";
$TABLE_KEY_TYPES_ARRAY[9]['id']						= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACHER_NAME']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACHER_TYPE_INTRO']		= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACHER_TYPE_DESIGN']	= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACHER_TYPE_EXAM']		= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACHER_TYPE_TRAIN']		= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACH_FREQUENCY_INTRO']	= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACH_FREQUENCY_DESIGN']	= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACH_FREQUENCY_EXAM']	= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[9]['TEACH_FREQUENCY_TRAIN']	= "varchar(15)";

$PAGE_INFO_ARRAY[10]['PAGE_NAME'] 					= "Classroom Schedule Manage";
$PAGE_INFO_ARRAY[10]['PAGE_NAME_IN_CHINESE'] 		= "教室课程表管理";
$PAGE_INFO_ARRAY[10]['FILE_NAME']					= "classroom_schedule_manage.php";
$PAGE_INFO_ARRAY[10]['TABLE_NAME']					= "CLASSROOM_SCHEDULE";
$TABLE_KEY_NAMES_ARRAY[10]['id']					= "id";
$TABLE_KEY_NAMES_ARRAY[10]['SEMESTER_WEEK']			= "SEMESTER_WEEK";
$TABLE_KEY_NAMES_ARRAY[10]['WEEK']					= "WEEK";
$TABLE_KEY_NAMES_ARRAY[10]['CLASSROOM_NAME']		= "CLASSROOM_NAME";
$TABLE_KEY_NAMES_ARRAY[10]['CLASSROOM_TYPE']		= "CLASSROOM_TYPE";
$TABLE_KEY_NAMES_ARRAY[10]['COURSE_PART_0']			= "COURSE_PART_0";
$TABLE_KEY_NAMES_ARRAY[10]['COURSE_PART_1']			= "COURSE_PART_1";
$TABLE_KEY_NAMES_ARRAY[10]['COURSE_PART_2']			= "COURSE_PART_2";
$TABLE_KEY_NAMES_ARRAY[10]['COURSE_PART_3']			= "COURSE_PART_3";
$TABLE_KEY_NAMES_ARRAY[10]['TEACHER_PART_0']		= "TEACHER_PART_0";
$TABLE_KEY_NAMES_ARRAY[10]['TEACHER_PART_1']		= "TEACHER_PART_1";
$TABLE_KEY_NAMES_ARRAY[10]['TEACHER_PART_2']		= "TEACHER_PART_2";
$TABLE_KEY_NAMES_ARRAY[10]['TEACHER_PART_3']		= "TEACHER_PART_3";
$TABLE_KEY_NAMES_ARRAY[10]['CLASS_PART_0']			= "CLASS_PART_0";
$TABLE_KEY_NAMES_ARRAY[10]['CLASS_PART_1']			= "CLASS_PART_1";
$TABLE_KEY_NAMES_ARRAY[10]['CLASS_PART_3']			= "CLASS_PART_2";
$TABLE_KEY_NAMES_ARRAY[10]['CLASS_PART_2']			= "CLASS_PART_3";
$TABLE_KEY_TYPES_ARRAY[10]['id']					= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[10]['SEMESTER_WEEK']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['WEEK']					= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['CLASSROOM_NAME']		= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['CLASSROOM_TYPE']		= "varchar(15)";	
$TABLE_KEY_TYPES_ARRAY[10]['COURSE_PART_0']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['COURSE_PART_1']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['COURSE_PART_2']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['COURSE_PART_3']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['TEACHER_PART_0']		= "varchar(15)";	
$TABLE_KEY_TYPES_ARRAY[10]['TEACHER_PART_1']		= "varchar(15)";	
$TABLE_KEY_TYPES_ARRAY[10]['TEACHER_PART_2']		= "varchar(15)";	
$TABLE_KEY_TYPES_ARRAY[10]['TEACHER_PART_3']		= "varchar(15)";	
$TABLE_KEY_TYPES_ARRAY[10]['CLASS_PART_0']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['CLASS_PART_1']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['CLASS_PART_2']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[10]['CLASS_PART_3']			= "varchar(15)";
$GRID_KEY_NAMES_ARRAY[10]['id']						= "ID";
$GRID_KEY_NAMES_ARRAY[10]['SEMESTER_WEEK']			= "学期周";
$GRID_KEY_NAMES_ARRAY[10]['WEEK']					= "星期";
$GRID_KEY_NAMES_ARRAY[10]['CLASSROOM_NAME']			= "教室名称";			
$GRID_KEY_NAMES_ARRAY[10]['CLASSROOM_TYPE']			= "教室类型";
$GRID_KEY_NAMES_ARRAY[10]['COURSE_PART_0']			= "12节";			
$GRID_KEY_NAMES_ARRAY[10]['COURSE_PART_1']			= "34节";	
$GRID_KEY_NAMES_ARRAY[10]['COURSE_PART_2']			= "56节";	
$GRID_KEY_NAMES_ARRAY[10]['COURSE_PART_3']			= "78节";	
$GRID_KEY_NAMES_ARRAY[10]['TEACHER_PART_0']			= "12节教师";
$GRID_KEY_NAMES_ARRAY[10]['TEACHER_PART_1']			= "34节教师";
$GRID_KEY_NAMES_ARRAY[10]['TEACHER_PART_2']			= "56节教师";
$GRID_KEY_NAMES_ARRAY[10]['TEACHER_PART_3']			= "78节教师";
$GRID_KEY_NAMES_ARRAY[10]['CLASS_PART_0']			= "12节班级";		
$GRID_KEY_NAMES_ARRAY[10]['CLASS_PART_1']			= "34节班级";		
$GRID_KEY_NAMES_ARRAY[10]['CLASS_PART_3']			= "56节班级";		
$GRID_KEY_NAMES_ARRAY[10]['CLASS_PART_2']			= "78节班级";		

//11

//12
$PAGE_INFO_ARRAY[12]['PAGE_NAME'] 					= "Students Schedule Manage";
$PAGE_INFO_ARRAY[12]['PAGE_NAME_IN_CHINESE'] 		= "学生课表管理";
$PAGE_INFO_ARRAY[12]['FILE_NAME']					= "students_schedule_manage.php";
$PAGE_INFO_ARRAY[12]['TABLE_NAME']					= "STUDENTS_SCHEDULE";
$TABLE_KEY_NAMES_ARRAY[12]['id']					= "id";
$TABLE_KEY_NAMES_ARRAY[12]['CLASS_NAME']			= "CLASS_NAME";
$TABLE_KEY_NAMES_ARRAY[12]['SEMESTER_WEEK']			= "SEMESTER_WEEK";
$TABLE_KEY_NAMES_ARRAY[12]['WEEK']					= "WEEK";
$TABLE_KEY_NAMES_ARRAY[12]['COURSE_PART_0']			= "COURSE_PART_0";
$TABLE_KEY_NAMES_ARRAY[12]['COURSE_PART_1']			= "COURSE_PART_1";
$TABLE_KEY_NAMES_ARRAY[12]['COURSE_PART_2']			= "COURSE_PART_2";
$TABLE_KEY_NAMES_ARRAY[12]['COURSE_PART_3']			= "COURSE_PART_3";
$TABLE_KEY_TYPES_ARRAY[12]['id']					= "int NOT NULL AUTO_INCREMENT, PRIMARY KEY(id)";
$TABLE_KEY_TYPES_ARRAY[12]['CLASS_NAME']			= "varchar(15)";			
$TABLE_KEY_TYPES_ARRAY[12]['SEMESTER_WEEK']			= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[12]['WEEK']					= "varchar(15)";
$TABLE_KEY_TYPES_ARRAY[12]['COURSE_PART_0']			= "varchar(150)";
$TABLE_KEY_TYPES_ARRAY[12]['COURSE_PART_1']			= "varchar(150)";
$TABLE_KEY_TYPES_ARRAY[12]['COURSE_PART_2']			= "varchar(150)";
$TABLE_KEY_TYPES_ARRAY[12]['COURSE_PART_3']			= "varchar(150)";
$GRID_KEY_NAMES_ARRAY[12]['id']						= "ID";
$GRID_KEY_NAMES_ARRAY[12]['CLASS_NAME']				= "班级名称";
$GRID_KEY_NAMES_ARRAY[12]['SEMESTER_WEEK']			= "学期周";
$GRID_KEY_NAMES_ARRAY[12]['WEEK']					= "星期";
$GRID_KEY_NAMES_ARRAY[12]['COURSE_PART_0']			= "12节";
$GRID_KEY_NAMES_ARRAY[12]['COURSE_PART_1']			= "34节";
$GRID_KEY_NAMES_ARRAY[12]['COURSE_PART_2']			= "56节";
$GRID_KEY_NAMES_ARRAY[12]['COURSE_PART_3']			= "78节";

$PAGE_INFO_ARRAY[13]['PAGE_NAME'] 					= "Course and Course type Import";
$PAGE_INFO_ARRAY[13]['PAGE_NAME_IN_CHINESE'] 		= "课程及模块导入";
$PAGE_INFO_ARRAY[13]['FILE_NAME']					= "course_import.php";

$PAGE_INFO_ARRAY[14]['PAGE_NAME'] 					= "Class and Weeks Schedule Import";
$PAGE_INFO_ARRAY[14]['PAGE_NAME_IN_CHINESE'] 		= "班级及周课表导入";
$PAGE_INFO_ARRAY[14]['FILE_NAME']					= "class_import.php";

//Fin.
?>